jobs/yoctoproject.md, people/belen-pena.md
Adding myself to the people and posting the
first job. The Yocto Project needs a favicon
for Toaster.
Signed-off-by: Belen Barros Pena <belenbarrospena@gmail.com>
=> A new person and a new job

jobs/2014-02-okfn-frontend-developer-UX-designer
A couple ppl wanna approve this please? :)
=> added OKFN job

jobs/guitarix.md
=>  * add guitarix job

jobs/guitarix.md
Hi 
Many thanks to the job-board, a great initiative. 
I' could solved my issue and find a designer who take over the job. 
regards
hermann
=>  * status solved

README.md
In response to the current README and somewhat [this](https://github.com/opensourcedesign/job-board/issues/4)
=> added a semi-functional job board to readme, until something better is conceived

README.md, jobs/2015-03-cocoa-dev-to-opensource-espionage.md
- Simplified links in README
- Added Espionage job to list in README
- Updated job description.
=> Updated README, improved links, and updated job description.

README.md
=> Fix typo and broken link

jobs/2015-03-ui-design-for-raml2html-api-docs-generator.md
Looking for a designer to work on an open source project that generated HTML docs from RAML files that describe API's. Thanks!
=> Added raml2html job

README.md, _config.yml, _includes/header.html, _layouts/jobs.html, index.html, jobs/2015-02-okfn-frontend-developer-UX-designer.md, jobs/2015-03-UX-audit-and-facelift-of-Pencil.md, jobs/2015-03-cocoa-dev-to-opensource-espionage.md, jobs/2015-03-ui-design-for-raml2html-api-docs-generator.md, jobs/2015-03-ui-design-for-remotestorage-connect-widget-dialog.md, jobs/chat-secure.md, jobs/democracy-club.md, jobs/guitarix.md, jobs/red-hat_senior-ixd.md, jobs/yoctoproject.md
* Changed name of URL (cause it's reserved by Jekyll)
* Exclude the sample post from the jobs loop
* Reveal details on actual job listings
* Remove listing from readme.md
=> More info on front page

_config.yml
Also correcting the Twitter username. cc @simonv3
=> change "Open Source Jobs" to specify "Open Source Design"

jobs/qtpass.md
Adding a request for help with the qtpass project
=> Adding qtpass

.gitignore, job-template.md
* Add gitignore
* Add contact, contributing, and contributors fields.
=> Add contact

_includes/header.html
=> add Events page link to Jobs page

_config.yml, jobs/2015-06-05-three-js-job.md
As a follow up to #39, here's a PR with the job added back in, just in the right spot.
Let me know if the job description is right @CrasHog!
This PR also contains a permalink structure.
=> Add three js job

jobs/2015-06-23-etherpad.md
=> Etherpad Job posting

README.md, jobs/2015-06-25-designing-codeofconductlink-site---code-of-conduct-link.markdown, jobs/2015-07-10-design-openfarm-mascot---openfarm.markdown
=> Add codeofconductlink and OpenFarm

jobs/2015-07-15-android-metta-app.md
Thank you for providing this space for posting ads!
=> Now solved!

jobs/2015-06-23-etherpad.md
Improve Job title and added links to Etherpad project page.
=> Update 2015-06-23-etherpad.md title and links

jobs/2015-03-yoctoproject.md
=> Set Yocto Project to closed

2015-10-08-valueflows-logo.md
i figure might as well open the invite here in case anyone is interested, even though we're at a very early stage of our project.
ref: https://github.com/valueflows/valueflows/issues/38
=> add job for Value Flows

jobs/2015-10-08-valueflows-logo.md
there were some minor issues caused by the easiest Submit a Job workflow, fixed in https://github.com/opensourcedesign/jobs/pull/62
=> fix Value Flows job

jobs/2015-10-26-PhotoFlow-UI_UX-Enhancement.md
This way, the information will be visible in the job page (until issue #30 will be solved).
=> Added contact and web resources in text body

index.html
`https://github.com/opensourcedesign/jobs#job-board` -> `https://github.com/opensourcedesign/jobs#jobs`
`our Github repository` -> `our GitHub repository`
=> Change `our Github repository` Hash to the Readme

jobs2016-02-02-habitica.md
http://habitica.wikia.com/wiki/Contributing_to_Habitica#Designers
=> Add Habitica call for designers

jobs/YYY-MM-DD-ChooseAJobTitle.md
Jobs UX designer, Quebec, Qc, canada
=> 2016-02-09-UX-designer-savoirfairelinux.md

jobs/2016-03-10-create-a-logo-for-a-large-oss-project---react-boilerplate.markdown
react-boilerplate needs a logo, and this seems like the perfect place to advertise that fact!
=> Add the react-boilerplate logo

feed.xml, index.html
=> Only show 'searching' projects

jobs/2016-07-06-awesome-cryptography-twitter-logo.md
[`awesome-cryptography`](https://github.com/sobolevn/awesome-cryptography) is looking for a logo for our [twitter account](https://twitter.com/awe_crypto_bot).
See job description for details.
=> Added `awesome-cryptography` twitter account job

jobs/2016-07-29-RadioWitness.io-alpha-release-branding.md
added job posting for https://radiowitness.io alpha release branding.
=> RadioWitness.io - alpha release branding

jobs/YYY-MM-DD-ChooseAJobTitle.md
Hello! Just wanted to submit this, hope it's alright :)
Have a lovely day ahead!
=> chuaccheng-UIUXGraphicDesign-fun.md

jobs/2016-10-10-BasicIncome-Through-Group-Income-Frontend-Lead.md
okTurtles Foundation job listing for [Group Income](https://groupincome.org) — Voluntary Basic Income — Frontend Lead.
=> Basic Income through Group Income — Frontend Lead

jobs/2016-10-13-OONI-UX-Designer.md
Note the torproject.org link is not yet live, but should be in the next couple hours.
=> Add job posting for OONI UX Designer

jobs/2016-10-22-gngr-logo.md
=> Request logo design for gngr

jobs/2016-06-11-Create-A-Logo-For-git-secret.md
https://github.com/opensourcedesign/jobs/pull/92
=> Git Secret Job solved

jobs/2016-06-28-Patchwork-logo.md
https://github.com/opensourcedesign/jobs/pull/94
=> Patchwork logo solved

jobs/2016-07-06-awesome-cryptography-twitter-logo.md
=> Awesome Crypto Twitter solved

jobs/2016-07-23-ElixirLangMoscow-website-and-identity.md
https://github.com/opensourcedesign/jobs/pull/98
=> Elixir Lang Moscow solved

jobs/2016-04-19-VisualDesignerForTorStyleGuide.md
cc @ameellio @elioqoshi @bnvk this is solved, right?
=> mark Tor job as solved

jobs/2017-01-14-inkscape-open-symbols-ux-ui.md
Inkscape Open Symbols are open source SVG symbol sets that can be used as Inkscape symbols.
The project has grown recently with many contributions
We want to design a website (and branding) to help other users understand the project, install the symbols and how to contribute.
=> Add inkscape Open Symbols job

jobs/2017-02-06-InspectorWidget.md
Hi,
Thanks for letting me pitch InspectorWidget yesterday in the Open Source Design devroom at FOSDEM!
Here is a pull request for design jobs that would be highly beneficial for InspectorWidget.
Best regards,
Christian
=> Add InspectorWidget job

css/custom.css
Nav bar taking extra spaces as you can see here
https://drive.google.com/file/d/0B7-ba5abIMaoUzIyQnc2dTNiSEk/view?usp=sharing
fixed it
=> Extra nav bar space fixed.

jobs/2017-04-28-frontend-branding-for-composerci.md
I already designed the frontend myself :smile:
=> Update ComposerCI Job details

_includes/head.html
Equivalent of https://github.com/opensourcedesign/opensourcedesign.github.io/pull/112
=> Fix title and favicon link

jobs/2017-04-28-frontend-branding-for-composerci.md
See https://github.com/opensourcedesign/jobs/pull/212#issuecomment-298967616
=> Add a valid URL to ComposerCI Job

jobs/2017-04-28-frontend-branding-for-dependenci.md
=> Rename ComposerCI to DependenCI

jobs/2017-04-20-branding-for-libreoffice-60.md
=> Fix typo in e-mail address

jobs/2017-08-05-kiwi-irc-web-client-design.md
=> Markdown does not work in How to apply

jobs/2017-07-09-create-a-logo-for-recase-project.md
Reverts opensourcedesign/jobs#234
=> Revert "Delete 2017-07-09-create-a-logo-for-recase-project.md"

jobs/2017-07-09-create-a-logo-for-recase-project.md
See comment https://github.com/opensourcedesign/jobs/pull/231#issuecomment-316420663 
Also PRs:
- https://github.com/opensourcedesign/jobs/pull/234
- https://github.com/opensourcedesign/jobs/pull/238
=> [misc] Changing status

jobs/2017-12-07-stickers-and-t-shirts.md
Fixing the description that did not appear on the website.
=> Fix 2017-12-07-stickers-and-t-shirts description.md

_layouts/jobs.html
Attempt to fix https://github.com/opensourcedesign/opensourcedesign.github.io/issues/176
Please review @AnXh3L0 @evalica @ei8fdb :)
=> Change Discourse embed from http to https

_includes/header.html
https://github.com/opensourcedesign/opensourcedesign.github.io/issues/167
=> Missing menu entries when going to Jobs, Events #167

jobs/2018-09-06-new-official-logo-for-bromite.md
If you don't mind I would like to remove the email address because I saw a sensible increase in spam :)
=> Remove email address

README.md
According to https://github.com/opensourcedesign/opensourcedesign.github.io/issues/70#issuecomment-270925924
=> Adding documentation about the job status values

jobs/2019-09-27-illustrations-how-tails-work.md
Hi,
I tried to submit a new job offer through the online form but I got 2 crash errors from Heroku. So here is a pull request for the same thing. I'm not sure what's best for you :)
=> New Job - Illustrations on what is Tails and how it works

jobs/2019-10-30-help-designing-a-distinguishable-clean-and-modern-looking-logo-and-color-scheme.md
2019-10-30-help-designing-a-distinguishable-clean-and-modern-looking-logo-and-color-scheme.md
`status` from `searching` >> `closed`
=> Update status for 2019-10-30-help... mailchain theme

jobs/2020-04-29-.md
Setting up a GH handle from the website when submitting the entry led me to some json error page; also the how_to_apply fields look very broken in the page, hopefully this will clean it up a bit...
=> tweaks to make this look decent

jobs/2020-05-26-new-logo-to-go-with-major-app-update.md
Deadline passed; job now closed.
=> Change status of AntennaPod logo job

jobs/2020-07-29-ui-ux-design-for-an-open-source-handheld-console-proof-of-concept.md
Improve job post and remove email (as it is visible as a plain text)
=> Update job post

jobs/2019-11-15-update-the-web-theme-for-plc4x.md
=> Closing job listing

jobs/2020-10-18-symbolic-icons-app-icon-for-gnome-health.md
The job has been fullfilled in the meantime
=> Close 2020-10-18-symbolic-icons-app-icon-for-gnome-health

README.md, jobs/2021-01-05-logo-icons-for-monado-xr-vr-ar-runtime.md
I had put a Markdown list of links in the links box in the form, but that didn't get translated into the final file correctly. No matter what I did, it wouldn't show up right so I just put them into the body of the page/description. The form should probably be revised, but I'm not familiar enough with how this works to do that.
I also added the hint that jekyll is used: I had tried rake first since I saw a Rakefile, but realized there were no tasks for jekyll in the rakefile, only an (abandoned?) command-line way of adding a new job posting.
=> Fix Monado posting, add a little to the README.

README.md
Fixed a small typo on the README. Also, new to contributing to open source so I wanted to practice but actually help.
=> Fixed a typo!

jobs/2021-01-28-ui-ux-designer-to-work-with-us.md
I've made some changes to improve a job post I previously made. This is based on feedback that I received that the job post wasn't clear.
=> Improve Book Project job post

jobs/2020-06-15-.md
Closing this job that I opened as the project is in hiatus.
=> Update 2020-06-15-.md - Closing job

jobs/2020-09-29-.md
Changing to 'solved' to unlist this job as it was filled by a community member :)
=> Update 2020-09-29-.md - Solved

jobs/2020-07-04-icon-needed-for-open-source-emoji-picker-emote.md
Tom has agreed it can be 'solved' https://github.com/tom-james-watson/Emote/issues/12#issuecomment-789930882
=> Update 2020-07-04-icon-needed-for-open-source-emoji-picker-emote.md - solved

jobs/2021-01-06-.md
Requester replied to an email saying they had two designers respond and offer help :)
=> Update 2021-01-06-.md - Solved

jobs/2020-03-12-.md
The original poster has confirmed this can be closed
=> Update 2020-03-12-.md - solved

jobs/2020-03-11-.md
The original poster has confirmed this can be closed
=> Update 2020-03-11-.md - solved

jobs/2020-07-24-.md
Original poster happy for this to be closed!
=> Update 2020-07-24-.md - solved

jobs/2020-06-18-new-logo-needed-for-safrano-opensource-odata-library.md
…y.md
Original poster has a contribution they're happy with :D
=> Update 2020-06-18-new-logo-needed-for-safrano-opensource-odata-librar… - solved

jobs/2020-06-02-design-logo-for-open-source-pm-issue-tracking-software.md
…are.md
Original poster is happy to close and received contributions that are now live on their website :D
=> Update 2020-06-02-design-logo-for-open-source-pm-issue-tracking-softw… - solved

jobs/2020-10-30-.md
The poster said it can be closed
=> Update 2020-10-30-.md - solved

jobs/2020-12-07-design-review-and-implementation.md
Original poster found a designer to help them and they are happy :) solving this listing!
=> Update 2020-12-07-design-review-and-implementation.md - solved

jobs/2020-06-21-pick-low-hanging-fruits-in-our-gatsby-project.md
The requester is ok with being closed/solved. They received some submissions but not exactly what they wanted I followed up via email with an offer to help with defining any new job posts/requests on OSD.net/jobs :)
=> Update 2020-06-21-pick-low-hanging-fruits-in-our-gatsby-project.md - Solved

jobs/2019-03-22-ux-engineer-m-f-d-2-years.md
closed as it's a very old job post and the application page is no longer live
=> Update 2019-03-22-ux-engineer-m-f-d-2-years.md - solved

jobs/2021-01-05-logo-icons-for-monado-xr-vr-ar-runtime.md
changing to 'solved' as the requester has received design support via: https://gitlab.freedesktop.org/monado/monado/-/issues/110 and is happy 😄
=> Update 2021-01-05-logo-icons-for-monado-xr-vr-ar-runtime.md - Solved

jobs/2020-04-20-.md
Changing to solved as the original poster indicated on discourse they were no looking for help:https://discourse.opensourcedesign.net/t/jobs-ux-designer-for-our-open-source-project-urbannoise/1720/3
=> Update 2020-04-20-.md - solved

jobs/2020-08-10-junior-developer.md
Closing as the job posting on their website has expired
=> Update 2020-08-10-junior-developer.md - solved

jobs/2020-08-10-scrum-master-mentor.md
Closing as the job posting on their website has expired
=> Update 2020-08-10-scrum-master-mentor.md - solved

jobs/2020-08-10-senior-designer.md
Closing as the job posting on their website has expired
=> Update 2020-08-10-senior-designer.md solved

jobs/2020-11-23-call-for-proposals-brand-visual-designer.md
Closing as the due date on the posting is gone 'December 4, 2020.'
=> Update 2020-11-23-call-for-proposals-brand-visual-designer.md - solved

jobs/2019-03-22-working-student-ux-m-f-d.md
closed as it's a very old job post and the application page is no longer live
=> Update 2019-03-22-working-student-ux-m-f-d.md - solved

jobs/2020-05-20-full-time-ux-ui-designer-at-open-collective.md
=> Update 2020-05-20-full-time-ux-ui-designer-at-open-collective.md - solved

jobs/2019-02-03-improving-the-two-webpages-of-a-simple-web-interface-to-a-metadata-removal-tool.md
…e-to-a-metadata-removal-tool.md
requester got their design needs solved :D
=> Update 2019-02-03-improving-the-two-webpages-of-a-simple-web-interfac… - solved

jobs/2020-07-24-new-website-to-reflect-our-services-and-commitment-to-the-foss-community.md
…to-the-foss-community.md
Requester happy to close out!
=> Update 2020-07-24-new-website-to-reflect-our-services-and-commitment-… - solved

jobs/2021-02-19-android-and-desktop-icon-for-hexadecimal-editor.md
Not sure if this the correct way how to request update on job status...
=> Android and desktop icon for hexadecimal editor - Icon accepted

jobs/2019-01-21-material-design-including-logo-and-assets.md
=> Update 2019-01-21-material-design-including-logo-and-assets.md - solved

jobs/2019-06-09-flat-infographic-illustrations-icons.md
=> Update 2019-06-09-flat-infographic-illustrations-icons.md - solved

jobs/2019-05-23-.md
=> Update 2019-05-23-.md - solved

jobs/2019-05-17-looking-for-designers-for-our-dental-ehr-system.md
=> Update 2019-05-17-looking-for-designers-for-our-dental-ehr-system.md - solved

jobs/2019-12-06-rework-the-search-and-replace-dialog.md
=> Update 2019-12-06-rework-the-search-and-replace-dialog.md - solved

jobs/2019-09-27-illustrations-how-tails-work.md
=> Update 2019-09-27-illustrations-how-tails-work.md - solved

jobs/2018-01-25-help-to-fix-design-issues-of-logo-for-print.md
=> Update 2018-01-25-help-to-fix-design-issues-of-logo-for-print.md -solved

jobs/2018-01-30-design-lead.md
=> Update 2018-01-30-design-lead.md - solved

jobs/2018-02-06-design-a-chameleon-outline-for-the-opensuse-conference.md
…nce.md
requester happy to close
=> Update 2018-02-06-design-a-chameleon-outline-for-the-opensuse-confere… - solved

jobs/2019-02-25-fix-broken-design-of-the-c-geo-android-geocaching-app.md
…pp.md
Requester happy to close!
=> Update 2019-02-25-fix-broken-design-of-the-c-geo-android-geocaching-a… - solved

jobs/2018-03-21-logo-and-icons-review-of-our-remote-desktop-client.md
=> Update 2018-03-21-logo-and-icons-review-of-our-remote-desktop-client.md - solved

jobs/2018-05-25-mobile-ux-designer.md
=> Update 2018-05-25-mobile-ux-designer.md - solved

jobs/2021-02-07-design-contributors-wanted.md
=> Update 2021-02-07-design-contributors-wanted.md - Updated

jobs/2021-02-07-design-contributors-wanted.md
This version of this job kind of broke fro some reason to I submitted again :)
=> Update 2021-02-07-design-contributors-wanted.md - closed

jobs/2021-05-11-ux-design-call-for-proposals.md
Tin from the OAS project here, the position has been filled, closing the vacancy.
=> Closing 2021-05-11-ux-design-call-for-proposals.md

jobs/2021-01-28-ui-ux-designer-to-work-with-us.md
Update job post for the Book Project with some images and a link to our new design page.
=> Update job post with images and link

jobs/2016-05-02-Mozilla-Community-Design.md
=> Update 2016-05-02-Mozilla-Community-Design.md - solved

jobs/2018-09-07-create-an-svg-of-the-jugaadfest-logo.md
=> Update 2018-09-07-create-an-svg-of-the-jugaadfest-logo.md - solved

jobs/2017-01-14-inkscape-open-symbols-ux-ui.md
=> Update 2017-01-14-inkscape-open-symbols-ux-ui.md - solved

jobs/2017-07-05-ux-interaction-designer-wikipediaf-m.md
job post likely has closed now
=> Update 2017-07-05-ux-interaction-designer-wikipediaf-m.md - solved

jobs/2018-12-19-design-a-logo-for-an-open-source-code-quality-tool.md
Job posters email address bounced :/
=> Update 2018-12-19-design-a-logo-for-an-open-source-code-quality-tool.md - solved

jobs/2017-02-05-Repository configuration for code analysis as a service using coala.md
…vice using coala.md
no email to double check but old issue - closing
=> Update 2017-02-05-Repository configuration for code analysis as a ser… - solved

jobs/2017-02-05-Usability Testing with coala.md
no contact and old job - closing
=> Update 2017-02-05-Usability Testing with coala.md - solved

jobs/2017-02-07-slide about GNU Taler for RMS's deck.md
=> Update 2017-02-07-slide about GNU Taler for RMS's deck.md - solved

jobs/2017-02-09-Intern UX-Design -Research.md
=> Update 2017-02-09-Intern UX-Design -Research.md - sovled

jobs/2018-11-26-designer-full-time-san-francisco.md
Job post on their internal site has been taken down
=> Update 2018-11-26-designer-full-time-san-francisco.md - solved

jobs/2017-02-09-UX intern.md
=> Update 2017-02-09-UX intern.md - solved

jobs/2018-07-30-.md
Solved in the discourse post: https://discourse.opensourcedesign.net/t/jobs-face-lifting-new-design-for-angular-material-web-application/704/6
=> Update 2018-07-30-.md - solved

jobs/2018-03-26-sticker-pack-artwork.md
=> Update 2018-03-26-sticker-pack-artwork.md - solved

jobs/2015-06-05-three-js-job.md
=> Update 2015-06-05-three-js-job.md - solved

jobs/2016-11-21-retroarch-assets.md
poster happy to close via discord
=> Update 2016-11-21-retroarch-assets.md - solved

jobs/2016-08-29-OwnPassDesigner.md
=> Update 2016-08-29-OwnPassDesigner.md - solved

jobs/2017-12-21-logo-for-an-opensource-genetics-sanger-trace-viewer.md
=> Update 2017-12-21-logo-for-an-opensource-genetics-sanger-trace-viewer.md - solved

jobs/2017-01-25-Logo design for the Astroid Mail User Agent.md
=> Update 2017-01-25-Logo design for the Astroid Mail User Agent.md - solved

jobs/2018-07-26-.md
Poster agreed can close! they don't contribute to that project anymore
=> Update 2018-07-26-.md - solved

jobs/2016-02-09-UXDesigner-SavoireFaire.md
=> Update 2016-02-09-UXDesigner-SavoireFaire.md - solved

jobs/2016-10-22-gngr-logo.md
=> Update 2016-10-22-gngr-logo.md - solved

jobs/2017-10-06-design-a-new-theme-for-discourse.md
=> Update 2017-10-06-design-a-new-theme-for-discourse.md - solved

jobs/2018-02-05-design-website-for-muonium.md
=> Update 2018-02-05-design-website-for-muonium.md - solved

jobs/2017-12-20-ux-designer.md
=> Update 2017-12-20-ux-designer.md - solved

jobs/2017-11-10-frontend-polishing.md
=> Update 2017-11-10-frontend-polishing.md - solved

jobs/2018-05-05-create-an-avatar-for-the-wip-bot.md
Looks clearly filled here: https://github.com/wip/app/issues/67
=> Update 2018-05-05-create-an-avatar-for-the-wip-bot.md - solved

jobs/2017-08-05-kiwi-irc-web-client-design.md
=> Update 2017-08-05-kiwi-irc-web-client-design.md - solved

jobs/2017-10-15-design-a-simple-way-to-show-an-facebook-user-their-own-information-diet.md
…own-information-diet.md
poster happy to close
=> Update 2017-10-15-design-a-simple-way-to-show-an-facebook-user-their-… - solved

jobs/2016-10-10-the-best-node-mvc-framework-crocodilejs.md
=> Update 2016-10-10-the-best-node-mvc-framework-crocodilejs.md - solved

jobs/2018-11-30-design-a-logo-for-copytranslator-a-very-useful-open-source-translation-tool.md
…-source-translation-tool.md
poster happy to close
=> Update 2018-11-30-design-a-logo-for-copytranslator-a-very-useful-open… - solved

jobs/2016-08-03-MakeSilexWebsiteBuilderTemplatesResponsive.md
=> Update 2016-08-03-MakeSilexWebsiteBuilderTemplatesResponsive.md - solved

jobs/2016-11-28-Logo-for-Libreflip.md
=> Update 2016-11-28-Logo-for-Libreflip.md - solved

jobs/2017-02-15-Designer - Art Director needed for a new demo included in Drupal core.md
…ded in Drupal core.md
Poster happy to close
=> Update 2017-02-15-Designer - Art Director needed for a new demo inclu… - solved

jobs/2017-05-11-ajv-github-pages-design-for-desktop-and-mobile.md
=> Update 2017-05-11-ajv-github-pages-design-for-desktop-and-mobile.md - solved

jobs/2015-03-20-internet-of-things-dashboard.md
=> Update 2015-03-20-internet-of-things-dashboard.md - solved

jobs/2015-06-25-designing-code-of-conduct-link-site.md
=> Update 2015-06-25-designing-code-of-conduct-link-site.md - solved

jobs/2015-09-SVG-plant-icons.md
=> Update 2015-09-SVG-plant-icons.md - solved

jobs/2017-07-31-graphic-designer-for-application-and-business-assets.md
=> Update 2017-07-31-graphic-designer-for-application-and-business-asset… - solved

jobs/2017-02-06-InspectorWidget.md
=> Update 2017-02-06-InspectorWidget.md - solved

jobs/2017-02-27-graphic-designer-for-an-culinary-app.md
=> Update 2017-02-27-graphic-designer-for-an-culinary-app.md - solved

jobs/2015-10-08-valueflows.md
=> Update 2015-10-08-valueflows.md - solved

jobs/2017-02-28-sinonjs-homepage-design.md
=> Update 2017-02-28-sinonjs-homepage-design.md - solved

jobs/2017-12-07-stickers-and-t-shirts.md
=> Update 2017-12-07-stickers-and-t-shirts.md - solved

jobs/2018-10-29-.md
=> Update 2018-10-29-.md - solved

jobs/2021-01-28-book-project-ui-ux.md
- Fix broken link
- Rename file to make it more concise
=> Fix link & rename file

jobs/2018-06-11-secushare-design-logo.md
Did not reply to email asking if still needed
=> Update 2018-06-11-secushare-design-logo.md - solved

jobs/2015-09-circuits-logo-redesign.md
=> Update 2015-09-circuits-logo-redesign.md - solved

jobs/2015-10-26-PhotoFlow-UI_UX-Enhancement.md
=> Update 2015-10-26-PhotoFlow-UI_UX-Enhancement.md - solved

jobs/2015-11-19-phanbook.md
=> Update 2015-11-19-phanbook.md - solved

jobs/2015-11-25-Frontend-Dev-for-Jolocom.md
=> Update 2015-11-25-Frontend-Dev-for-Jolocom.md - solved

jobs/2015-08-10-navit-current-ui-refresh.md
=> Update 2015-08-10-navit-current-ui-refresh.md - solved

jobs/2015-08-openvz-brand-guideline.md
=> Update 2015-08-openvz-brand-guideline.md - solved

jobs/2015-04-28-mustache.md
=> Update 2015-04-28-mustache.md - solved

jobs/2015-06-23-etherpad.md
=> Update 2015-06-23-etherpad.md - solved

jobs/2015-03-cocoa-dev-to-opensource-espionage.md
=> Update 2015-03-cocoa-dev-to-opensource-espionage.md - solved

jobs/2015-03-UX-audit-and-facelift-of-Pencil.md
=> Update 2015-03-UX-audit-and-facelift-of-Pencil.md - solved

jobs/2015-03-chat-secure.md
=> Update 2015-03-chat-secure.md - solved

jobs/2016-10-13-OONI-UX-Designer.md
=> Update 2016-10-13-OONI-UX-Designer.md - solved

jobs/2016-08-31-design-the-simplest-landing-page.md
=> Update 2016-08-31-design-the-simplest-landing-page.md - solved

jobs/2016-07-05-PPS2-UI-Design.md
=> Update 2016-07-05-PPS2-UI-Design.md - solved

jobs/2016-06-13-openSUSE_101_shirt.md
=> Update 2016-06-13-openSUSE_101_shirt.md - solved

jobs/2016-03-14-the-coral-project-mozilla-ux-designer.md
=> Update 2016-03-14-the-coral-project-mozilla-ux-designer.md - solved

jobs/2016-04-02-logo-for-graphql-go.md
=> Update 2016-04-02-logo-for-graphql-go.md - solved

jobs/2017-12-30-hospitalized-patient-management-module-mockups.md
=> Update 2017-12-30-hospitalized-patient-management-module-mockups.md - solved

jobs/2017-11-09-logo-design-for-human-machine-interface-in-education.md
=> Update 2017-11-09-logo-design-for-human-machine-interface-in-educatio… - solved

jobs/2017-11-08-design-help-needed-for-an-open-source-free-charity-based-social-platform.md
=> Update 2017-11-08-design-help-needed-for-an-open-source-free-charity-… - solved

jobs/2017-10-15-open-technology-fund-usability-lab.md
=> Update 2017-10-15-open-technology-fund-usability-lab.md - solved

jobs/2017-10-23-we-need-illustration-logo.md
=> Update 2017-10-23-we-need-illustration-logo.md - solved

jobs/2017-09-03-logo-and-web-design-for-factopolis.md
=> Update 2017-09-03-logo-and-web-design-for-factopolis.md - solved

jobs/2017-10-01-mochajsorg-facelift-and-logo.md
=> Update 2017-10-01-mochajsorg-facelift-and-logo.md - solved

jobs/2017-07-11-a-banner-850mm-x-2000mm-feature-open-source-ai-in-education-at-the-makerfaire-xian-and-singapore.md
…ducation-at-the-makerfaire-xian-and-singapore.md
=> Update 2017-07-11-a-banner-850mm-x-2000mm-feature-open-source-ai-in-e… - solved

jobs/2017-07-21-redesign-maven-website.md
=> Update 2017-07-21-redesign-maven-website.md- solved

jobs/2017-06-15-call-for-new-activemq-project-logo.md
=> Update 2017-06-15-call-for-new-activemq-project-logo.md - solved

jobs/2017-05-30-style-the-website.md
=> Update 2017-05-30-style-the-website.md - solved

jobs/2017-06-28-libreoffice-mascot.md
=> Update 2017-06-28-libreoffice-mascot.md - solved

jobs/2017-02-08-Polish look of website.md
=> Update 2017-02-08-Polish look of website.md - solved

jobs/2017-04-28-frontend-branding-for-dependenci.md
=> Update 2017-04-28-frontend-branding-for-dependenci.md - solved

jobs/2017-03-15-Enhance-UI-Aspects-in-Conversations-app.md
=> Update 2017-03-15-Enhance-UI-Aspects-in-Conversations-app.md - solved

jobs/2017-04-03-web-designer-for-tellform.md
=> Update 2017-04-03-web-designer-for-tellform.md - solved

jobs/2017-05-09-design-new-emojis.md
=> Update 2017-05-09-design-new-emojis.md - solved

jobs/2017-02-14-Frontend redesign for Orgmanager.md
=> Update 2017-02-14-Frontend redesign for Orgmanager.md - solved

jobs/2017-02-17-graphic-designer-for-genomics-application-logo.md
=> Update 2017-02-17-graphic-designer-for-genomics-application-logo.md - solved

jobs/2017-02-22-android-passman-app-design.md
=> Update 2017-02-22-android-passman-app-design.md - solved

jobs/2017-01-30-Graphic design for FOSSASIA conference (t-shirt + some artwork).md
=> Update 2017-01-30-Graphic design for FOSSASIA conference (t-shirt + s… - solved

jobs/2017-01-23-Web & Logo Designer for an Idea Sharing Platform.md
=> Update 2017-01-23-Web & Logo Designer for an Idea Sharing Platform.md - solved

jobs/2017-01-23-Graphic designer for OpenScore.md
=> Update 2017-01-23-Graphic designer for OpenScore.md - solved

jobs/2017-01-02-gnome-two-factor-auth.md
=> Update 2017-01-02-gnome-two-factor-auth.md - solved

jobs/2018-12-24-redesign-a-logo-for-an-open-source-data-generation-tool.md
=> Update 2018-12-24-redesign-a-logo-for-an-open-source-data-generation-… - solved

jobs/2018-11-29-design-a-logo-for-open-source-project.md
=> Update 2018-11-29-design-a-logo-for-open-source-project.md - solved

jobs/2017-01-24-UI Designer for account management interface project.md
=> Update 2017-01-24-UI Designer for account management interface projec… - solved

jobs/2018-12-13-.md
=> Update 2018-12-13-.md - solved

jobs/2018-08-01-create-an-illustration-for-404-not-found-page.md
=> Update 2018-08-01-create-an-illustration-for-404-not-found-page.md - solved

jobs/2018-11-01-design-review-of-our-operative-system-graphic-designs.md
=> Update 2018-11-01-design-review-of-our-operative-system-graphic-desig… - solved

jobs/2018-11-03-re-designing-adonisjs-from-scratch.md
=> Update 2018-11-03-re-designing-adonisjs-from-scratch.md - solved

jobs/2018-11-08-logo-for-cmints.md
=> Update 2018-11-08-logo-for-cmints.md - solved

jobs/2021-04-22-design-contributors-for-open-food-systems-platform-ux-research-ui-visual-design-build-your-own-project-etc.md
…ux-research-ui-visual-design-build-your-own-project-etc.md
No longer onboarding vols!
=> Update 2021-04-22-design-contributors-for-open-food-systems-platform-… - solved

jobs/2021-01-14-senior-ux-designer-at-ubuntu-canonical.md
Job posting now closed on their website
=> Update 2021-01-14-senior-ux-designer-at-ubuntu-canonical.md - solved

jobs/2019-02-06-designing-logo-for-our-oss-org-named-mfossociety.md
=> Update 2019-02-06-designing-logo-for-our-oss-org-named-mfossociety.md - solved

jobs/2021-01-28-book-project-ui.md
- Switch from looking for a UI/UX designer to only UI designers
- Fix broken link
=> Change to UI post

jobs/2021-08-20-ux-ui-research-on-gamifying-the-product.md
Hello,
Can you please disable the RestQA job ❤️.
Thank you
=> Disable the restqa job

jobs/2021-04-22-sustain-oss-community-tee-shirt-design.md
job was filled in 2021 requested asked to close
=> Update 2021-04-22-sustain-oss-community-tee-shirt-design.md - closed

jobs/-.md
closing as it's from 2018 and the last update and comms were back in feb 2021
=> closing as it's from 2018

jobs/2021-11-09-giga-user-experience-design-specialist.md
=> Update 2021-11-09-giga-user-experience-design-specialist.md - closed

jobs/2021-08-02-illustrator-animator.md, jobs/2021-08-02-web-designer-developer.md
Thanks for the poke @Erioldoesdesign, they only recently were filled actually. :)
=> Closing Nextcloud jobs as they have recently been filled

jobs/2022-05-11-hedgedoc-2.md
We got in contact with some people. Thanks :)
=> Close HedgeDoc 2

jobs/2022-02-05-help-antennapod-understand-podcast-listener-users-and-improve.md
We've found our contributor :)
(Line endings were automatically updated by GitHub it said, dunno why.)
=> Close AntennaPod research posting

jobs/2022-02-23-simple-product-designer.md
We do not need more applicants. Thanks!
=> Changed status to "closed" for Simple job

jobs/2022-12-20-jenkins-newsletter.md
I am manually creating this PR for a job that Alyssa Tong tried to post but couldn't since our staticman isn't working. They had sent the details of the job in email, so creating a PR based on that information.
=> New Job - Jenkins Newsletter

jobs/2022-10-01-design-a-logo-and-branding-for-a-non-profit-working-on-open-source.md
We have worked with a designer to create our logo for @openprivacytech
just opening a PR since the job is completed!
Thanks
=> Job completed

_config.yml, index.html
A new plugin was added and the redirect link was set in the front matter of the index.html file.
=> Added redirect plugin and redirect to the forum thread

jobs/2021-04-24-.md, jobs/2021-04-24-web-design-for-qutebrowser-a-web-browser-for-power-users.md
Priorities shifted - I plan to get back to at least one of those in the future, but for now, let's close it.
=> Close qutebrowser job postings for now

jobs/2024-03-19-ux-redesign.md
We have found someone interested, thank you for your intrest
=> Closing inventree

jobs/2024-09-29-design-improvement-of-our-landing-page.md
=> Close Design improvement of our landing page

jobs/2025-01-07-orchard-core-cms-admin-ux-revamp.md
Note that GitHub also normalized the line endings.
=> Closing Orchard Core CMS admin UX revamp

jobs/2025-04-08-ui-ux-designer.md
Closing as position was filled.
=> Close Nextcloud UI/UX Designer job posting
